#creo la lista con las preguntas a realizar
preguntas = []
#creo un diccionario por cada pregunta donde almaceno el numero index de la pregunta "a mano", la pregunta, la respuesta correcta y las respuestas que el usuario puede elegir
p1 = dict(index=1, indexPadre=0, pregunta='Eres un joven trabajador, desde los 14 años que te encuentras trabajando sin vacaciones y has pasado por distintos rubros, desde ayudante de cocina y camarero en un comedor comunitario, hasta telemarketer y mecánico de bicicletas. Un día se te ocurre hacer deporte, y en lo que practicas conoces a una persona, Marcelo, con quien muy pocas veces has hablado, pero tienen buena relación, él te invita a su cumpleaños que se celebrará el próximo fin de semana para lo cual no es necesario llevar dinero, Marcelo dejo toda la cena paga. ¿Asistirás?')
p2 = dict(index=2, indexPadre=11, pregunta='Llegaste al bar, Marcelo te saluda con un enérgico abrazo (como las 3 veces que se han visto) y comienza la cena. Entre risas y anécdotas de la infancia entre sus pares, vos sos el único que no tiene conocidos en común, estas sólo y aumentan el aburrimiento y las ganas de irte, ¿Qué haces?')
p3 = dict(index=3, indexPadre=22, pregunta='Continúas en el lugar, ya casi llegando al final, Marcelo se para y exclama Los que quieran trabajar que se acerquen conmigo! ¿Qué haces?')
p4 = dict(index=4, indexPadre=13, pregunta='Al acercarte a la mesa donde estaba Marcelo, él te sienta a su lado y comienza a relatarles a los aislados, que el trabajo consta de trabajos de oficina, fotocopias, teléfono, papelerío y el sueldo duplicaba tu salario actual, como así también la jornada laboral es de 6 horas. Ves que la mayoría al rededor se mostraron escépticos a lo que Marcelo les decía, y comenzaste a dudar, ¿Qué haces ahora?')
p5 = dict(index=5, indexPadre=14, pregunta='Has aceptado la oferta de Marcelo a medias, luego de comentarle tu situación le preguntaste en que empresa estaría trabajando y te respondió que era una institución estatal, por lo que sentiste incertidumbre, pero a la semana le confirmaste hicieron los tramites y luego de algunos meses comenzaste a trabajar, era la sucursal 39 de Villa Urquiza, te quedaba súper cerca de tu casa bastaba con caminar. Al llegar el primer día te entrevista la jefa de administración, Chort, quien te da el turno de la noche, el cual lo tienes ocupado por la carrera de administración de empresas que estas cursando, es noviembre y casi terminas el año con todas las materias aprobadas. Chort te da dos opciones, te quedas o te vas?')
p6 = dict(index=6, indexPadre=25, pregunta='Bien, oficialmente eres empleado en la sucursal 39, llevas ahora casi 3 años trabajando allí y has pasado por varias funciones, ahora como correo, tuviste que dejar de estudiar la carrera de administración, dirección de orquesta, criminalística ya te habías resignado a quedarte ahí estancado, cuando el jefe de la sucursal, Cisneros, jefe general te encuentra en la puerta antes de hacer tu recorrida diaria y te pregunta. ¿Sos de los míos?')
p7 = dict(index=7, indexPadre=16, pregunta='Tras haberle respondido que si, a Cisneros lo transfieren a la sucursal 45, que queda en villa devoto, tu ahora eres correo intersucu4sal, y generalmente recorres el microcentro entregando memorandos y notas de gran variedad. Un día esperabas el subterráneo para volver a tu sucursal a entregas el correo entrante cuando recibís un llamado, era Cisneros ofreciéndote ir a la sucursal 45 para administrar las redes de ese lugar. No tenés conocimientos en absoluto al respecto, hace meses nació tu hija y no tenés dinero para costear un curso. ¿Aceptas?')
p8 = dict(index=8, indexPadre=17, pregunta='Te transfirieron a la sucursal 45, en el camino leíste algo sobre redes, pero muy poco como para comprender, pasaron 4 meses, conseguiste algo de dinero, muy poco, pero encontraste un curso que parece tener algo rescatable, todos los cursos superaban los 3mil pesos, y este salía 600, con mucho sacrificio estarías realizándolo')
p9 = dict(index=9, indexPadre=33, pregunta='Le consultas a Cisneros, y tras leerlo le dice a su chofer "necesitamos gente así", dame un segundo. En ese momento habla con otra persona por teléfono, al finalizar te da una dirección donde presentarte. Resulta ser que es de un curso de redes en cisco, un curso ccna1, no sabes cómo se come eso, pero vas igual, total ya estas jugado, el jefe pago el curso para que vayas. Terminaste el curso, administras las redes de la sucursal pero lo vuelven a transferir, a todo esto, al subjefe de la sucursal también lo transfieren, y se llevó con él a 2 ayudantes, de los cuales 1 recordó que habías hecho un Excel donde el ingresaba el DNI del empleado y podía visualizarse su función, horarios, puesto jerárquico y si hacia horas extra o no y te llama, en su área de fármacos necesitan personal idóneo en el uso de computadoras, y no hay nadie disponible, la sucursal queda en San Cristóbal. ¿Querés ir a esa nueva área?')
p10 = dict(index=10, indexPadre=29, pregunta='Llego la transferencia al área de fármacos, no sabían que hacer ni como trabajar, estableciste una metodología de trabajo, varios modelos de estadística y toda la información la cargabas tu solo, al año transfirieron más personas para ayudarte, aprovechaste la buena relación con tu jefe y te autorizo a ir en horario laboral a realizar tu curso de programación. Comenzaste a desarrollar un sistema para alivianar el trabajo, porque todo lo hacían en planillas Excel. Tu jefe hablo con gente del área de sistemas para echarte una mano a terminarlo. Luego de la visita de Walter, personal del área de sistemas, quien luego de ver lo que desarrollabas te ofreció ir a esa área, pero dejo la respuesta abierta. Te llamo ese día por la tarde y te consulto de manera más informal, ¿Aceptas ir al área de sistemas?')
p34 = dict(index=34, indexPadre=30, pregunta='No se me ocurría que historia contar, a falta de creatividad opte por usar una parte de lo que fui recorriendo en estos 5 años, y también, como fui aprovechando distintas oportunidades que se me fueron dando, hasta el día de hoy sigue así, actualmente trabajo en el área de sistemas de policía de la ciudad, el trabajo que me ofreció Marcelo, al día de hoy amigo cercano, era en policía de la ciudad, trabaje en las comisarías 39 y 45, vino el traspaso a la ciudad y me llevaron al área de drogas, donde generaba estadísticas, y el resto ya fue contado. ')
p11 = dict(index=11, indexPadre=1, pregunta='No lo conozco lo suficiente como para que se sienta con la confianza de invitarme a una ocasión especial como es el cumpleaños, pero me tuvo en cuenta, asistiré')
p12 = dict(index=12, indexPadre=2, pregunta='Digo que ya es tarde y que debo ir a trabajar temprano al otro día, me voy')
p13 = dict(index=13, indexPadre=3, pregunta='Me acercare, a ver qué propuesta hay, las cosas van mal en la bicicletería donde trabajas actualmente')
p14 = dict(index=14, indexPadre=4, pregunta='Le comenté mi situación en la bicicletería y que estaría aceptando su oferta, pero no sabía en qué lugar estaría trabajando, pero dados esos beneficios, no podía perder la oportunidad')
p15 = dict(index=15, indexPadre=5, pregunta='Me voy')
p16 = dict(index=16, indexPadre=6, pregunta='Yo, empleado de la sucursal 39, usted jefe, jerárquicamente usted es mi jefe, eso pensaste, y simplemente respondiste si señor')
p17 = dict(index=17, indexPadre=7, pregunta='Le digo que acepto, y luego buscare información en internet sobre redes, no creo que sea tan complicado')
p18 = dict(index=18, indexPadre=8, pregunta='Me anoto y comienzo a realizar el curso, y sorprendo a mis compañeros y al jefe')
p19 = dict(index=19, indexPadre=9, pregunta='Es muy lejos, y no quiero la ve4dad, estoy más cómodo acá en l sucursal 45')
p20 = dict(index=20, indexPadre=10, pregunta='Me siento más seguro donde estoy, ya conozco el trabajo, no soy imprescindible pero cualquier error y demás soy el primero en consultar, en este año que paso logre ganar la aceptación y confianza de los superiores de mi jefe')
p21 = dict(index=21, indexPadre=1, pregunta='No lo conozco lo suficiente como para que se sienta con la confianza de invitarme a una ocasión especial como es el cumpleaños, y la verdad es que me da flojera ir, le diré el día anterior que surgió algo y no podré asistir')
p22 = dict(index=22, indexPadre=2, pregunta='Continúo en la cena, aun no se han sentado a charlar, pero me gustaría formar parte del ambiente jocoso')
p23 = dict(index=23, indexPadre=3, pregunta='Intentas hablas con la amiga de su primo, llevo una minifalda que parte la tierra')
p24 = dict(index=24, indexPadre=4, pregunta='Te parece raro trabajar menos tiempo por más plata, estas en argentina y esas cosas no ocurren, te negaste a su oferta')
p25 = dict(index=25, indexPadre=5, pregunta='Me quedo')
p26 = dict(index=26, indexPadre=6, pregunta='No jefe, la verdad es que estoy resignado, no estoy conforme con los cambios de horario y función, no puedo estudiar nada, muy frustrante y desconforme, ¿Me ofrece algo mejor?')
p27 = dict(index=27, indexPadre=7, pregunta='Le digo que me gustaría ir, pero no sé nada sobre redes, no tengo problemas en realizar el curso, pero mi situación económica no me permite costearlo')
p28 = dict(index=28, indexPadre=8, pregunta='En otro momento será')
p29 = dict(index=29, indexPadre=9, pregunta='Esta bien, mientas pueda trabajar, mejor. Acá en la sucursal 45 no me daban trabajo por ser "el hijo del jefe" y estoy aburrido')
p30 = dict(index=30, indexPadre=10, pregunta='Ya hay un grupo armado, una forma de trabajo y dentro de todo, ya se organizan, no soy necesario acá, vamos al área de sistemas, estoy viendo que me agrada, pero aún no se mucho')
p31 = dict(index=31, indexPadre=3, pregunta='Sigues comiendo y tomando cerveza')
p32 = dict(index=32, indexPadre=7, pregunta='No señor, muchas gracias por el llamado')
p33 = dict(index=33, indexPadre=8, pregunta='Antes de gastar la plata le pregunto al jefe sobre el programa de estudio, él es instruido en la materia y sabrá decirme si conviene o no, no hay que gastar dinero en vano')
p35 = dict(index=35, indexPadre=21, pregunta='Llegó el día del cumpleaños y tienes muchas ganas de ir a tomar una cerveza, es una lástima que no tengas plata y que no hayas ido, será la próxima')
p36 = dict(index=36, indexPadre=12, pregunta='Te fuiste y el colectivo no vino más, terminaste yendo caminando a casa con mucho frio, te dio anginas y estuviste una semana en cama')
p37 = dict(index=37, indexPadre=23, pregunta='No era necesario quedar en ridículo, pero para no perder la costumbre lo hiciste, la chica te mando a freír churros')
p38 = dict(index=38, indexPadre=24, pregunta='Le preguntaste a Marcelo si era una broma, te levantaste y fuiste por otra cerveza, una lástima no poder ver las oportunidades cuando se presentan')
p39 = dict(index=39, indexPadre=15, pregunta='y bueno, te fuiste, seguiste trabajando como heladero un par de años más, y después comenzaste a seguir rotando de profesiones (para no perder la costumbre)')
p40 = dict(index=40, indexPadre=26, pregunta='Te mandaron a una sucursal que está en lugano, y te queda re a contramano, una macana, a veces hay que darse cuenta de lo que uno tiene antes de perderlo, y cuesta')
p41 = dict(index=41, indexPadre=27, pregunta='lo bueno de decir la verdad es que a la mayoría le cae mal, no te llevo para la otra sucursal y seguiste rotando los horarios, una lástima')
p42 = dict(index=42, indexPadre=18, pregunta='gastaste plata al divino botón, el jefe te iba a pagar un curso en cisco de 5 Lucas, y bueno, antes de gastar dinero es mejor preguntar con personas que sepan un poco más que uno y tener vistas de otros ángulos para llegar a una mejor conclusión')
p43 = dict(index=43, indexPadre=29, pregunta='te quedaste en la 45, a tu jefe lo mandaron a otra sucursal y jamás te volvió a llevar, volviste a tener horarios malísimos')
p44 = dict(index=44, indexPadre=20, pregunta='seguiste igual, sacando estadísticas, haciendo informes desde las 7 hasta las 01 del otro día, una pena, en sistemas te habría ido mejor')
p45 = dict(index=45, indexPadre=31, pregunta='Terrible pedo te agarraste, terminaste yendo al hospital y te pusieron una inyección, contrólate!')
p46 = dict(index=46, indexPadre=32, pregunta='cuando un jefe te lleva, la pasas bárbaro, que lastima')
p47 = dict(index=47, indexPadre=28, pregunta='y bueno, no hiciste nada, el jefe te tildo de vago y volviste a cambiar de horarios y funciones, una macana')

preguntas.append(p1)
preguntas.append(p2)
preguntas.append(p3)
preguntas.append(p4)
preguntas.append(p5)
preguntas.append(p6)
preguntas.append(p7)
preguntas.append(p8)
preguntas.append(p9)
preguntas.append(p10)
preguntas.append(p34)
preguntas.append(p11)
preguntas.append(p12)
preguntas.append(p13)
preguntas.append(p14)
preguntas.append(p15)
preguntas.append(p16)
preguntas.append(p17)
preguntas.append(p18)
preguntas.append(p19)
preguntas.append(p20)
preguntas.append(p21)
preguntas.append(p22)
preguntas.append(p23)
preguntas.append(p24)
preguntas.append(p25)
preguntas.append(p26)
preguntas.append(p27)
preguntas.append(p28)
preguntas.append(p29)
preguntas.append(p30)
preguntas.append(p31)
preguntas.append(p32)
preguntas.append(p33)
preguntas.append(p35)
preguntas.append(p36)
preguntas.append(p37)
preguntas.append(p38)
preguntas.append(p39)
preguntas.append(p40)
preguntas.append(p41)
preguntas.append(p42)
preguntas.append(p43)
preguntas.append(p44)
preguntas.append(p45)
preguntas.append(p46)
preguntas.append(p47)